### ISSUE TITLE
Warning DONKEY

### ISSUE THREAD

**Issue by Goetheus** [mcmonkey4eva/Sentinel#104]
Hi mcmonkey!

I hope everything goes well for you :)
I come for report an error :/

**Versions:**
_Spigot_: 1.10.2 R0.1
_Citizens2_: 2.0.21 (build 1437)
_Sentinel_: 0.9 (build 70)

I can't create a sentinel NPC because I get this error. This happen when I type "/trait Sentinel" for the first time on the NPC.

`[23:10:06 WARN]: java.lang.NoSuchFieldError: DONKEY
[23:10:06 WARN]:        at org.mcmonkey.sentinel.SentinelTarget.<clinit>(SentinelTarget.java:10)
[23:10:06 WARN]:        at org.mcmonkey.sentinel.SentinelTrait.onAttach(SentinelTrait.java:384)
[23:10:06 WARN]:        at net.citizensnpcs.api.trait.Trait.linkToNPC(Trait.java:46)
[23:10:06 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:100)
[23:10:06 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:89)
[23:10:06 WARN]:        at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
[23:10:06 WARN]:        at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
[23:10:06 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:10:06 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:10:06 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:10:06 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[23:10:06 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[23:10:06 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[23:10:06 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[23:10:06 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
[23:10:06 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:10:06 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:10:06 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[23:10:06 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
[23:10:06 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
[23:10:06 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:10:06 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:10:06 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[23:10:06 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[23:10:06 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[23:10:06 WARN]:        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[23:10:06 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737)
[23:10:06 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
[23:10:06 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673)
[23:10:06 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572)
[23:10:06 WARN]:        at java.lang.Thread.run(Unknown Source)`

If I type "/trait Sentinel" after, I get a new warning

`[23:12:11 WARN]: java.lang.NoClassDefFoundError: Could not initialize class org.mcmonkey.sentinel.SentinelTarget
[23:12:11 WARN]:        at org.mcmonkey.sentinel.SentinelTrait.onAttach(SentinelTrait.java:384)
[23:12:11 WARN]:        at net.citizensnpcs.api.trait.Trait.linkToNPC(Trait.java:46)
[23:12:11 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:100)
[23:12:11 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:89)
[23:12:11 WARN]:        at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
[23:12:11 WARN]:        at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
[23:12:11 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:12:11 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:12:11 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:12:11 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[23:12:11 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[23:12:11 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[23:12:11 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[23:12:11 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
[23:12:11 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:12:11 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:12:11 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[23:12:11 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
[23:12:11 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
[23:12:11 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:12:11 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:12:11 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[23:12:11 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[23:12:11 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[23:12:11 WARN]:        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[23:12:11 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737)
[23:12:11 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
[23:12:11 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673)
[23:12:11 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572)
[23:12:11 WARN]:        at java.lang.Thread.run(Unknown Source)`

On bukkit, the 0.9 sentinel's version is annoted compatible with 1.10.
Before, I used the 0.6 version with Citizens2 (2.0.19), and it was work well... But I tried with the two latest versions because in the 0.6, Monsters don't attack/target sentinel NPC !

Thank you very much in advance for help!
Kiss <3

**Comment by mcmonkey4eva** [comment]
On Bukkit it's labeled
`B: Sentinel 0.9 for MC 1.11 for 1.10 `
The 1.10 is just there because BukkitDev literally did not have a 1.11 option at time of upload. The 1.11 part is the correct one.
For 1.10, use 0.8, which can be grabbed here: http://ci.citizensnpcs.co/job/Sentinel/69/ alongside Citizens 2.0.20 or 2.0.21


As for monsters targetting Sentinel NPCs: I'm not actually 100% sure what's up with that, sometimes they do and sometimes they don't. There's probably an option somewhere that might affect it, `/npc playerlist` is a particular suspect for whenever I get around to researching that. The Sentinel also needs to be definitively able to take damage from mobs for it to be targettable (No invincible, basically)

**Comment by Goetheus** [comment]
Hi mcmonkey!

Yes! It works with 0.8 and citizens 2.0.20 & 2.0.21! Thank you very much! 👍 

For mobs, yes, there are irregularities :
* Only Slimes and Magma cube target NPCs and attack them, but without any damage (no hurt).
* Zombie, Skeleton, Spider, Cave spider, Blaze, Zombie pigman, Enderman, Shulker, Witch, Silverfish, and endermite don't target or attack NPCs, unless they are attacked.
* Giant do not target or attack NPCs, even they are under attack.
* Ghast, Wither and Ender Dragon target and attack Sentinel NPCs.

WARNING: When Sentinel NPCs are killed by Ender Dragon, they are sometimes removed (kill + erase).

No error in console.

I noticed that Sentinel NPC (in events) are sometimes considered as players, sometimes not! I think the problem is here...

I hope it will help you!
Thank you for your work! It's amaaaazing :)
Kiss <3

**Comment by mcmonkey4eva** [comment]
Sentinel doesn't actually do anything to cause or prevent an NPC to or from being targeted. Any trouble there is at the Citizens or Minecraft level.
