### ISSUE TITLE
0.9 don't work。

### ISSUE THREAD

**Issue by lsz7575** [mcmonkey4eva/Sentinel#106]
my server 1.10.2    
0.6 it work。

[23:03:19 WARN]: java.lang.NoSuchFieldError: DONKEY
[23:03:19 WARN]: 	at org.mcmonkey.sentinel.SentinelTarget.<clinit>(SentinelTarget.java:10)
[23:03:19 WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.onAttach(SentinelTrait.java:384)
[23:03:19 WARN]: 	at net.citizensnpcs.api.trait.Trait.linkToNPC(Trait.java:46)
[23:03:19 WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:100)
[23:03:19 WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:89)
[23:03:19 WARN]: 	at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
[23:03:19 WARN]: 	at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
[23:03:19 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:03:19 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:03:19 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:03:19 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:03:19 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[23:03:19 WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[23:03:19 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[23:03:19 WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
[23:03:19 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:03:19 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[23:03:19 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[23:03:19 WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
[23:03:19 WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
[23:03:19 WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:03:19 WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:03:19 WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[23:03:19 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:03:19 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:03:19 WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[23:03:19 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[23:03:19 WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[23:03:19 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[23:03:19 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[23:03:19 WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by lsz7575** [comment]
On Bukkit it's labeled
B: Sentinel 0.9 for MC 1.11 for 1.10
The 1.10 is just there because BukkitDev literally did not have a 1.11 option at time of upload. The 1.11 part is the correct one.
For 1.10, use 0.8, which can be grabbed here: http://ci.citizensnpcs.co/job/Sentinel/69/ alongside Citizens 2.0.20 or 2.0.21

As for monsters targetting Sentinel NPCs: I'm not actually 100% sure what's up with that, sometimes they do and sometimes they don't. There's probably an option somewhere that might affect it, /npc playerlist is a particular suspect for whenever I get around to researching that. The Sentinel also needs to be definitively able to take damage from mobs for it to be targettable (No invincible, basically)
