### ISSUE TITLE
Spigot 1.10.2: Could not initialize class org.mcmonkey.sentinel.SentinelTarget

### ISSUE THREAD

**Issue by nidark** [mcmonkey4eva/Sentinel#111]
Hello,
I am using Spigot 1.10.2 and I am trying to create a Sentinel, with Citizens 2.0.21 (/2.0.20) and Sentinel 0.9.
After creating the NPC I am trying to "trait" the Sentinel, here is the error:
Same error if I try to create the NPC with the trait from the start  
Any hints ?

**[10:12:46 INFO]: Owner issued server command: /trait Sentinel**
[10:12:46 WARN]: java.lang.NoClassDefFoundError: Could not initialize class org.mcmonkey.sentinel.SentinelTarget
[10:12:46 WARN]:    at org.mcmonkey.sentinel.SentinelTrait.onAttach(SentinelTrait.java:384)
[10:12:46 WARN]:    at net.citizensnpcs.api.trait.Trait.linkToNPC(Trait.java:46)
[10:12:46 WARN]:    at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:100)
[10:12:46 WARN]:    at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:89)
[10:12:46 WARN]:    at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
[10:12:46 WARN]:    at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
[10:12:46 WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:12:46 WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:12:46 WARN]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:12:46 WARN]:    at java.lang.reflect.Method.invoke(Method.java:498)
[10:12:46 WARN]:    at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[10:12:46 WARN]:    at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[10:12:46 WARN]:    at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[10:12:46 WARN]:    at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
[10:12:46 WARN]:    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[10:12:46 WARN]:    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[10:12:46 WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[10:12:46 WARN]:    at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358)
[10:12:46 WARN]:    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193)
[10:12:46 WARN]:    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[10:12:46 WARN]:    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[10:12:46 WARN]:    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[10:12:46 WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[10:12:46 WARN]:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10:12:46 WARN]:    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[10:12:46 WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[10:12:46 WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[10:12:46 WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[10:12:46 WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[10:12:46 WARN]:    at java.lang.Thread.run(Thread.java:745)
>

**Comment by mcmonkey4eva** [comment]
Sentinel 0.9 is for 1.11, update your server to that, or
download Sentinel 0.8, which is for 1.10 http://ci.citizensnpcs.co/job/Sentinel/69/

**Comment by nidark** [comment]
Worked like a charm! TY!
