### ISSUE TITLE
Can not assign trait Sentinel

### ISSUE THREAD

**Issue by MacMinam** [mcmonkey4eva/Sentinel#117]
Hello,

I can not assign trait Sentinel to a npc. The chat box shows : 

_Please report this error: [See console]
java.lang.NoClassDefFoundError: Could not initialize class
org.mcmonkey.sentinel.SentinelTarget_

The console shows this : 
**[08:48:08] [Server thread/INFO]: MacMinam issued server command: /npc create bob
[08:48:20] [Server thread/INFO]: MacMinam issued server command: /trait Sentinel
[08:48:20] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class org.mcmonkey.sentinel.SentinelTarget
[08:48:20] [Server thread/WARN]:        at org.mcmonkey.sentinel.SentinelTrait.onAttach(SentinelTrait.java:414)
[08:48:20] [Server thread/WARN]:        at net.citizensnpcs.api.trait.Trait.linkToNPC(Trait.java:46)
[08:48:20] [Server thread/WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:100)
[08:48:20] [Server thread/WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:89)
[08:48:20] [Server thread/WARN]:        at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
[08:48:20] [Server thread/WARN]:        at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
[08:48:20] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:48:20] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08:48:20] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:48:20] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[08:48:20] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[08:48:20] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[08:48:20] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[08:48:20] [Server thread/WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
[08:48:20] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:48:20] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:48:20] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[08:48:20] [Server thread/WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358)
[08:48:20] [Server thread/WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193)
[08:48:20] [Server thread/WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[08:48:20] [Server thread/WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[08:48:20] [Server thread/WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[08:48:20] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[08:48:20] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[08:48:20] [Server thread/WARN]:        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[08:48:20] [Server thread/WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[08:48:20] [Server thread/WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[08:48:20] [Server thread/WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[08:48:20] [Server thread/WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[08:48:20] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)**

And nothing after that last line.

About my server:
this is a very small 1.10.2 spigot server. I am running 14 pugins : EssentialX (7 plugins), ClearLag, mcMMO, Vault, Citizens, Sentinel, Denizen and Quickshop.
Everything is working fine except the fact I can not use Sentinel (but the plugins loads fine at the server start).

Could someone help me solve this ?

Thank you very much !

MacMinam

**Comment by mcmonkey4eva** [comment]
You probably have the wrong build for 1.10. Find that here: https://wiki.citizensnpcs.co/Versions#Sentinel_Versions

**Comment by MacMinam** [comment]
Yes you're right.  It's working fine now.
Thanks again :)
