### ISSUE TITLE
Sentinels patrol path?

### ISSUE THREAD

**Issue by Firemonkey08** [mcmonkey4eva/Sentinel#135]
If I try to set an linear path to the waypoint provider, the NPc is going it, but an Sentinel dont get it. He´s walking one block and is going back immediately. Chasing is allowed, all options are default. Isn`t there a way to let them patrol?

**Comment by Firemonkey08** [comment]
The bug came with build 99. This is my error log:

[18:58:41] [Server thread/INFO]: [Citizens] Exception while updating 306: null.
[18:58:41] [Server thread/WARN]: java.lang.NullPointerException
[18:58:41] [Server thread/WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1652)
[18:58:41] [Server thread/WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1712)
[18:58:41] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430)
[18:58:41] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:268)
[18:58:41] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:140)
[18:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1530)
[18:58:41] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:969)
[18:58:41] [Server thread/WARN]: 	at net.citizensnpcs.util.NMS.tick(NMS.java:265)
[18:58:41] [Server thread/WARN]: 	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36)
[18:58:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:53)
[18:58:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[18:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:689)
[18:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360)
[18:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
[18:58:41] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
[18:58:41] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by Firemonkey08** [comment]
Can I be of any assistance to fix this bug? We would be so happy, when we can continue our work with the sentinel npcs on our server :)

**Comment by mcmonkey4eva** [comment]
Oh sorry, forgot this.

I pushed a potential fix to latest build - Jenkin 104

**Comment by Firemonkey08** [comment]
Working, thanks :)
