### ISSUE TITLE
log distance-error

### ISSUE THREAD

**Issue by Firemonkey08** [mcmonkey4eva/Sentinel#143]
Heyho,

my serverlog is full of sentinel warnings. The log has in 20 minutes 5.000.000 lines. The NPCs are in the world pvp. When I tp to this world pvp get all the warnings.
The error is:

[16:03:43] [Server thread/INFO]: Lucareli[/-------] logged in with entity id ------ at ([Creative]-1497.9299289427477, 69.0, 401.5314307220343)
[16:03:48] [Server thread/INFO]: Lucareli issued server command: /world pvp
[16:03:48] [Server thread/INFO]: [Citizens] Exception while updating 375: Cannot measure distance between pvp and Creative.
[16:03:48] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot measure distance between pvp and Creative
[16:03:48] [Server thread/WARN]: 	at org.bukkit.Location.distanceSquared(Location.java:456)
[16:03:48] [Server thread/WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1644)
[16:03:48] [Server thread/WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1717)
[16:03:48] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430)
[16:03:48] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:268)
[16:03:48] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:140)
[16:03:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1530)
[16:03:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.World.g(World.java:1508)
[16:03:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.WorldServer.l(WorldServer.java:638)
[16:03:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1340)
[16:03:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:616)
[16:03:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[16:03:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360)
[16:03:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650)
[16:03:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554)
[16:03:48] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by mcmonkey4eva** [comment]
Update to latest dev build (107+) off http://ci.citizensnpcs.co/job/Sentinel/

**Comment by Firemonkey08** [comment]
perfect, thanks :)
