### ISSUE TITLE
1.12 Error

### ISSUE THREAD

**Issue by xSzescianPL** [mcmonkey4eva/Sentinel#186]
[19:36:02] [Server thread/INFO]: [Sentinel] Enabling Sentinel v1.3.1 (build 119)
[19:36:02] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader Sentinel v1.3.1 (build 119)
[19:36:02] [Server thread/INFO]: [Sentinel] Sentinel loading...
[19:36:02] [Server thread/INFO]: class org.mcmonkey.sentinel.SentinelTrait
[19:36:02] [Server thread/ERROR]: Error occurred while enabling Sentinel v1.3.1 (build 119) (Is it up to date?)
java.lang.IllegalArgumentException: trait name already registered
	at net.citizensnpcs.npc.CitizensTraitFactory.registerTrait(CitizensTraitFactory.java:164) ~[?:?]
	at org.mcmonkey.sentinel.SentinelPlugin.onEnable(SentinelPlugin.java:72) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[MC.jar:git-Spigot-99c2a37-d35483b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [MC.jar:git-Spigot-99c2a37-d35483b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [MC.jar:git-Spigot-99c2a37-d35483b]
	at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.RestartCommand.execute(RestartCommand.java:124) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [MC.jar:git-Spigot-99c2a37-d35483b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [MC.jar:git-Spigot-99c2a37-d35483b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:645) [MC.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [MC.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [MC.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [MC.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [MC.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [MC.jar:git-Spigot-99c2a37-d35483b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [MC.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [MC.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [MC.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [MC.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [MC.jar:git-Spigot-99c2a37-d35483b]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

Server version:
[20:20:37] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-99c2a37-d35483b (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[20:20:37] [Server thread/INFO]: Checking version, please wait...
[20:20:37] [Thread-40/INFO]: You are 2 version(s)

**Comment by mcmonkey4eva** [comment]
A: You're using an old build http://ci.citizensnpcs.co/job/Sentinel/
B: You ... might have installed Sentinel twice? I can't think of any other reason it would try to register the trait twice.

Oh wait. You have plug man.
Get rid of plug man, that breaks everything :(
