### ISSUE TITLE
NPC health : error flooding console

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#204]
Hello,

Seems like line 1838 of SentinelTrait Class (runUpdate fonction) creates an error with numerous NPCs upon respawning. 

Error with paperspigot (last build), Citizens (build 1494 and some versions) and Sentinel (build 140 - 149).

```
12.09 22:03:50 [Server] INFO [Citizens] Exception while updating 4,953: Health must be between 0 and 20.0, but was 21.0. (attribute base value: 20.0, player: Garde).
12.09 22:03:50 [Server] WARN java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 21.0. (attribute base value: 20.0, player: Garde)
12.09 22:03:50 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:104)
12.09 22:03:50 [Server] WARN at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1838)
12.09 22:03:50 [Server] WARN at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1993)
12.09 22:03:50 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430)
12.09 22:03:50 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:268)
12.09 22:03:50 [Server] WARN at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:158)
12.09 22:03:50 [Server] WARN at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1755)
12.09 22:03:50 [Server] WARN at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1018)
12.09 22:03:50 [Server] WARN at net.citizensnpcs.util.NMS.tick(NMS.java:289)
```

**Comment by mcmonkey4eva** [comment]
The first thing Sentinel does on spawn is fix the health of the entity...
That looks like health value wasn't fixed appropriately for an NPC you have?
Do you have any plugins that might corrupt the max-health set for an NPC?

**Comment by Ferocimo** [comment]
It was a conflict with one of our plugin indeed. We will fix that on our end. Thank you.
