### ISSUE TITLE
NPE error on server start

### ISSUE THREAD

**Issue by Rocologo** [mcmonkey4eva/Sentinel#217]
Each time I start my test server I get this error:

[08:27:39 WARN]: [Sentinel] Task #26 for Sentinel v1.4.5 (build 157) generated an exception
java.lang.NullPointerException: null
	at org.mcmonkey.sentinel.SentinelPlugin$1.run(SentinelPlugin.java:86) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

Im using Citizens 2.0.22 Build 1496 and Sentinel 1.4.5 Build 154

**Comment by mcmonkey4eva** [comment]
Can you check for startup errors in your log?

**Comment by Rocologo** [comment]
I have no other errors in the server log:

https://pastebin.com/VMiqg5pR

**Comment by mcmonkey4eva** [comment]
My best guess is an incorrectly modified Citizens saves.yml, listing a target that isn't correctly named...

**Comment by Rocologo** [comment]
Hmmm I am infact saving data for my MasterMobHunter trait on the NPC's. May be one of them is broken. It is only on my test-server and I am pretty hard on the server...

**Comment by mcmonkey4eva** [comment]
Closing on the assumption this is fixed, if you have a remaining issue please reply below or open a new post.
