### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Fortepsai** [mcmonkey4eva/Sentinel#226]
[00:19:30 ERROR]: Could not pass event EntityDamageByEntityEvent to Citizens v2.0.22-SNAPSHOT (build 1498)
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:580) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:483) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:631) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:617) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityFireball.damageEntity(EntityFireball.java:171) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityArrow.a(EntityArrow.java:286) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityArrow.B_(EntityArrow.java:194) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityTippedArrow.B_(EntityTippedArrow.java:86) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftLargeFireball cannot be cast to org.bukkit.entity.LivingEntity
at org.mcmonkey.sentinel.SentinelTrait.whenAttacksHappened(SentinelTrait.java:390) ~[?:?]
at sun.reflect.GeneratedMethodAccessor180.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-4bd94dc-c765646]
... 21 more

**Comment by mcmonkey4eva** [comment]
Did you make a fireball NPC and give it the Sentinel trait?

**Comment by mcmonkey4eva** [comment]
Or are you maybe on an older version? http://ci.citizensnpcs.co/job/Sentinel/

**Comment by Midnight9746** [comment]
Most cases when I see the failed to pass event thing, it's just when the plugins exceeded the time in which one should of told citizens that an npc/player got hurt.

You could try making sure your server and the plugins are up to date and, from what a non-coder like me can tell, the error seems to be thrown when you use projectiles. There might be something interfering with how projectiles path/damage is delt with. Like I mean something might be blocking the damage and/or registering the path/entity as it's own, rather than have been shot by the player.

If the NPC is being hurt during theses errors then, that might be because of versions. As normal Minecraft and some plugins can track damage delt and register things like knockback and hp and use it as intended, but that doesn't necessarily means that citizens/sentinel picked up on it. Sure the server and other plugins say you hit the npc as it thinks it's a mob or player, but citizens/sentinel isn't picking up on the damage entity event.

The reason for the error, is most likely the versions of Citizens an the server. Why? Because as things update, methods are often changed to work differently, get removed, or updated to work better. Thus either your server or the plugin is using an older method and so it doesn't communicate property.

Such as:

"Could not pass event EntityDamageByEntityEvent to Citizens v2.0.22-SNAPSHOT (build 1498)
org.bukkit.event.EventException: null"

"EntityDamageByEntityEvent" might end up being called something like "DamageByEntityEvent" or like have "EntityDamagedByPlayerEvent" & "EntityDamageByMobEvent" to serve a purpose as to either change the methods name or give it capabilities, with the player/mob event one, those could allow coders to detect if a mob or player is hitting an entity.

If versions are outdated, they won't register (use or reconize) the events in use because the server isn't coded to run the events the plugin has.

That or you just have some grade A laaaag.... in which cases I call lagtastic.

**Comment by mcmonkey4eva** [comment]
Uh... none of that made much sense @Midnight9746 :/
My earlier replies are what it would be: Either a non-living NPC (a fireball NPC) was given a Sentinel trait for some hilarious reason, or just an outdated version of Sentinel.
For reference, the portion of the error you quoted doesn't even particularly matter much, the most significant area is:
`
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftLargeFireball cannot be cast to org.bukkit.entity.LivingEntity
at org.mcmonkey.sentinel.SentinelTrait.whenAttacksHappened(SentinelTrait.java:390) ~[?:?]`
That's the exact error at fault (a LargeFireball entity was assumed to be a Living entity by some section of code, but of course is not) and as well the exact line of code it occurred on (by pathname and line number).

**Comment by Fortepsai** [comment]
No i had no Fireball as npc and sentinel together .

**Comment by mcmonkey4eva** [comment]
Then your copy of the plugin was outdated.
