### ISSUE TITLE
angry wolf as sentinel

### ISSUE THREAD

**Issue by ScuroK** [mcmonkey4eva/Sentinel#239]
when i used an angry wolf as sentinel i got a ton of errors. 

unfortunately i only have a little piece of the errors:
[16:46:45 WARN]:        at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:2007)
[16:46:45 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:425)
[16:46:45 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:271)
[16:46:45 WARN]:        at net.citizensnpcs.nms.v1_12_R1.entity.WolfController$EntityWolfNPC.M(WolfController.java:187)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:670)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2097)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:507)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.EntityAgeable.n(EntityAgeable.java:158)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.EntityAnimal.n(EntityAnimal.java:27)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.EntityWolf.n(EntityWolf.java:152)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1946)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.EntityWolf.B_(EntityWolf.java:167)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.World.h(World.java:1601)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[16:46:45 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[16:46:45 WARN]:        at java.lang.Thread.run(Thread.java:748)
[16:46:45 INFO]: ScuroK issued server command: /npc remove
[16:47:12 INFO]: ScuroK issued server 

but maybe u can do some testing aswell. use a wolf-npc and do /npc wolf -a
then turn him into a sentinel and let him target players.

**Comment by mcmonkey4eva** [comment]
Make sure you're running the latest version - http://ci.citizensnpcs.co/job/Sentinel/
Post the FULL error message. Not a partial one!

**Comment by ScuroK** [comment]
i dont have the whole one anymore. but i thought a bad report (but hint) is better than not reporting. should be easy to reproduce.

**Comment by ScuroK** [comment]
oh i found it. enjoy the FULL one. (actually not because it was spammed so much so the file was over 10 mb large.....)

https://pastebin.com/crh4YyVR

**Comment by mcmonkey4eva** [comment]
I'll post it again, then...
Make sure you're running the latest version - http://ci.citizensnpcs.co/job/Sentinel/

**Comment by ScuroK** [comment]
does that mean you already fixed it? cool thx alot!

**Comment by mcmonkey4eva** [comment]
Don't report issues if you're not on latest builds of all related software. Issues may be fixed already, and if not already fixed, the issue report is useless as it contains inaccurate information.

If the issue occurs on a current build, reply below or open a new issue with updated information.

**Comment by ScuroK** [comment]
wow you seems to have a quite bad mood... do you even know what version i use?

**Comment by ScuroK** [comment]
yeah check it yourself if the bug still exists. cause i dont feel like anymore.

**Comment by mcmonkey4eva** [comment]
If you don't have the issue and "don't feel like" checking it further, then it isn't a relevant issue.

Further: if you "don't feel like" following through with issue reports or "don't feel like" keeping relevant software up to date prior to sending issue reports, don't send issue reports at all.

**Comment by ScuroK** [comment]
chill im gonna testing it now. :*

**Comment by ScuroK** [comment]
@mcmonkey4eva 
i tested with lates version: **the bug still exists..**

**Comment by ScuroK** [comment]
@mcmonkey4eva 
here is the complete log of what i did:

https://www.dropbox.com/s/gt5pxadh0vial6h/latest.log?dl=0
