### ISSUE TITLE
TPS Lagg when ranged sentinels hit mobs/targets

### ISSUE THREAD

**Issue by DangerAngel97** [mcmonkey4eva/Sentinel#254]
The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-642f6d2-6103339 (MC: 1.12.2) (Inplementing API version 1.12.2-R0.1-SNAPSHOT) Checking version, please wait... You are 81 version(s) behind
The output of command `/version citizens` on my server is: Citizens version 2.0.22-SNAPSHOT (build 1541) Website: http://www.citizensnpcs.co Authors: aPunch and fullwall
The output of command `/version sentinel` on my server is: Sentinel version 1.5.0 (build 170) Author: mcmonkey

The issue I'm having is a TPS drop when a sentinel starts shooting at monsters. TPS drops from ~19.999999 to as low as ~11.8 and never about ~15.4
And this is noticable in gameplay. I am spawning creepers and when the sentinel fires at the first I try to spawn more but nothing happens for about 1.5-3 seconds then they spawn. And while the creepers wander around and the sentinel fires a shot the creepers freezen then after the mob is killed, one shot with damage 300, the wandering creepers teleport. And the TPS ONLY drops if the arrow HITS the mob. If it misses then no TPS drop what so ever. So is there anything I should know about on how to fix this?

**Comment by DangerAngel97** [comment]
Here is the console when the sentinel hits the mob, in this case a creeper.

[22:14:08] [Server thread/ERROR]: Could not pass event EntityCombustByEntityEvent to Essentials v2.15.0.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.EntityArrow.a(EntityArrow.java:279) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.EntityArrow.B_(EntityArrow.java:194) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.EntityTippedArrow.B_(EntityTippedArrow.java:86) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at com.earth2me.essentials.EssentialsEntityListener.onEntityCombustByEntity(EssentialsEntityListener.java:131) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-642f6d2-6103339]
	... 15 more
[22:14:09] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Quests v3.3.2-b311
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:395) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1116) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.EntityCreeper.die(EntityCreeper.java:145) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.EntityArrow.a(EntityArrow.java:286) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.EntityArrow.B_(EntityArrow.java:194) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.EntityTippedArrow.B_(EntityTippedArrow.java:86) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at me.blackvein.quests.Quests.checkQuester(Quests.java:3787) ~[?:?]
	at me.blackvein.quests.PlayerListener.killMob(PlayerListener.java:499) ~[?:?]
	at me.blackvein.quests.PlayerListener.onEntityDeath(PlayerListener.java:468) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-642f6d2-6103339]
	... 20 more

**Comment by mcmonkey4eva** [comment]
That looks like you have multiple plugins (Essentials and Quests at least in your logs) glitching out in response to a creeper being killed by an arrow fired by an NPC.
It looks like they're both not able to handle the NPC as a player properly.
It might be some other plugin is in the middle damaging the event, or it might be the NPC is configured in some weird way. Settings on your NPC like `/npc playerlist` or similar might be fairly relevant here.

Try toggling that setting and looking over your NPC setup in general.
If you can't immediately get it to work, please open your `Citizens/saves.yml` file in a text editor and post the section of it that defines the NPC you have (or put the entire saves.yml file on https://pastebin.com/ and link that here if you prefer).

Also: you're running experimental 1.13 builds of Citizens (build 1559 is targeted for 1.13).
While that **should** work for 1.12, and it'd be ideal to ensure it's supported, if you're willing it'd be helpful to test whether the issue occurs on http://ci.citizensnpcs.co/job/Citizens2/1552/ as well (which is the final pre-1.13 build). If it stops the issue, that will narrow down possible things that could have gone wrong.

**Comment by DangerAngel97** [comment]
'72':
    metadata:
      player-skin-textures: eyJ0aW1lc3RhbXAiOjE1MzIyNzg4MjE4NDYsInByb2ZpbGVJZCI6ImFmYmE2NzdjOTI0ZTRmNzg5ODlmYWY5N2JjYjAyZDg3IiwicHJvZmlsZU5hbWUiOiJQb2xpY2VPZmZpY2VyIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83OTgxMzE4MTc1NWJiY2ZmNWE2Yjc2YmFiY2NkNWFkZGIxOGVlOWU0YzU1N2I3MWQzYmFlMjUwYjBiYTVhZWE4In19fQ==
      cached-skin-uuid-name: policeofficer
      cached-skin-uuid: afba677c-924e-4f78-989f-af97bcb02d87
      player-skin-name: policeofficer
      protected: true
      player-skin-signature: mIqcMga1jLZjvmPBdOJrsMxGlDQIdY+aOBRbb00K9oHpX4Uhpctfe6+TaJrnbruvmq+AmTjFt/9e/IHfE9gCFlP11n3BMDfGxrnP4GoNeJi7nkYTHBZioJzExQaB3jB5r44fh63rihtTiCGJm9F7sSpiFquEdFmEbjQ7X2jsqVCwYF8rca83yXqbEiA2xbAQWDTLtHERmDB1H7mNf+jfznATf1vBeYmij9vpizAtxUEHKStr+wlQhTFfnYwkLEaBEtoCDuOrqUCUajK7f4Vf1ENvOa/sKh0djcsEZjYIu9ZFk9fEC6MDeaL28PzsyB8+qVpn9Orcy3CipJrEnGWIybnQm4j0+nsfbR7n7DCkTa2g2vKQtD1TZLxXFqoUgye9gG74Jz/GhtOy9a1Jylnt/SeJBjJTg/E/ate8IknAl85HjK5szDmLvX9rRjTKjM/OT/ZtoiYetTsOQzevi+VAP4Ha/Dcy5G0SH8wqxvmqbogWxvLcBC1z43lyqO4et9psv2ORDvgn6B+n5ZE3Xd4NkoeN2OV28wNW0pMB8ypdJXWlP6qFvrImWIVfCnls0UzPvWcTy/EdPfwgdTp6I9NKC2HNb1x+PeeMQuREndQ7xQjmglH2CgA0GvV0MGBW1aXtL1IfWNbyORr9ZKUfyaZfXQvTc10ic6NZ1lTW7NAwrmI=
      collidable: false
    name: Spawn Protector
    uuid: f7e9fe90-b6dd-4ebb-82c1-28399563371b
    traits:
      sentinel:
        stats_ticksSpawned: 1266572
        stats_timesSpawned: 11
        stats_arrowsFired: 147
        stats_potionsThrow: 0
        stats_fireballsFired: 0
        stats_snowballsThrown: 0
        stats_eggsThrown: 0
        stats_skullsThrown: 0
        stats_pearlsUsed: 0
        stats_punches: 0
        stats_attackAttempts: 847
        stats_damageTaken: 0.0
        stats_damageGiven: 22092.0
        range: 199.0
        damage: 300.0
        armor: -1.0
        health: 20.0
        ranged_chase: false
        close_chase: true
        invincible: true
        fightback: true
        attackRate: 30
        attackRateRanged: 60
        healRate: 30
        guardingUpper: 0
        guardingLower: 0
        needsAmmo: false
        safeShot: true
        respawnTime: 100
        chaseRange: 100.0
        enemyDrops: false
        enemyTargetTime: 100
        speed: 1.0
        warning_text: ''
        greeting_text: ''
        greet_range: 10.0
        autoswitch: false
        accuracy: 0.0
        realistic: false
        reach: 3.0
        targets:
          '0': MONSTER
        ignores:
          '0': OWNER
      location:
        world: IceFactions
        x: '-113.5443'
        y: '73.0'
        z: '586.4913'
        yaw: '170.73699951171875'
        pitch: '0.0'
      inventory:
        '0':
          type: BOW
          amount: 1
          durability: 0
          mdata: 0
          meta:
            unbreakable: false
            repaircost: 0
          enchantments:
            ARROW_DAMAGE: 5
            ARROW_KNOCKBACK: 2
            DURABILITY: 3
            ARROW_FIRE: 1
            ARROW_INFINITE: 1
            MENDING: 1
      spawned: true
      equipment:
        hand:
          type: BOW
          amount: 1
          durability: 0
          mdata: 0
          meta:
            unbreakable: false
            repaircost: 0
          enchantments:
            ARROW_DAMAGE: 5
            ARROW_KNOCKBACK: 2
            DURABILITY: 3
            ARROW_FIRE: 1
            ARROW_INFINITE: 1
            MENDING: 1
      type: PLAYER
      gravity:
        enabled: false
      owner:
        owner: StormyIceLeopard
        uuid: b6d2ea2a-0ea9-4d5c-bbb4-89894e0188d5
    traitnames: inventory,type,owner,sentinel,spawned,equipment,location,gravity,mounttrait
    navigator:
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true

And I did use build 1552 and then I updated to the latest to see if that fixed anything. Sadly it didn't. I did try toggling that command but no results. Am going to look if there is an update for Quests and Essentials and see if that helps. I also do plan to update to 1.13 but I don't know how to do a world conversion.

**Comment by DangerAngel97** [comment]
Okay after updating Essentials, Quests, Downgrading Citizens, there is no more errors in console but I still got the TPS lagg on hit of the mob/target.

**Comment by mcmonkey4eva** [comment]
I glanced at the Quests source code earlier, and noticed they did not fix the error, but did **hide** the error. It still internally generates an exception, which is slow.
Can't say for sure that's the cause of lag. It'd be good to set up a java profiler like WarmRoast or VisualVM or any other capable Java profiler, as that's the only real way to diagnose lag issues.

**Comment by mcmonkey4eva** [comment]
VIsualVM is very basic and minimal and not really oriented towards user-friendliness.
WarmRoast ( https://github.com/sk89q/WarmRoast ) might be easier as it's meant specifically for minecraft server owners to benefit from (and, importantly, is a Java profiler and not a timing plugin or anything)

**Comment by DangerAngel97** [comment]
I can't get warmroast to launch.

**Comment by DangerAngel97** [comment]
Okay so I disabled the Quests Plugin and the issue is still there so it's not quests.

**Comment by mcmonkey4eva** [comment]
I don't think it's a Citizens issue, but it's really hard to say what it could be.

Perhaps since a good profiler isn't immediately working (I don't really know about how to fix WarmRoast errors, and the profilers I generally use are not public/free, unfortunately) perhaps a lower quality but somewhat helpful option might be good. Do you know how to record Spigot timings? (the `/timings` commands and system). It's not always super accurate but it might help at least figure out some direction of where the problem might be.

**Comment by DangerAngel97** [comment]
I know how to do timings but I don't know how to read them. Will do it right now then update this post with a link.

**Comment by DangerAngel97** [comment]
Here is the Link to timings.
https://www.spigotmc.org/go/timings?url=bepeminujo

**Comment by mcmonkey4eva** [comment]
Yeah seem to have some issues with WorldGuard there.
Possibly as mentioned in the red text there, you might have too little RAM for what you're running.
Beyond that, likely need to ask WorldGuard support folks for more help there. They might also know how to get WarmRoast working too, helpfully (same dev involved in both WG and WarmRoast).

Also you have `Spartan` running illegitimately (a bit of lag but more importantly is likely running malware on your server and may be disrupting other things)

**Comment by DangerAngel97** [comment]
Okay, it's not little RAM because there is about 1500MB free of given/allocated RAM. And Spartan is my anti-cheat, not malware.

**Comment by mcmonkey4eva** [comment]
Well your anti-cheat is (or contains) malware.
You can see on the timings report this stuff:
`Task: ?$$Lambda$28/1700452378(interval 50)`
`me.vagdedes.spartan.?.?::?(InventoryClickEvent)`
That's obfuscated/hidden activity, which is basically a guarantee of either malware or just a really terrible developer.

**Comment by DangerAngel97** [comment]
https://www.spigotmc.org/resources/spartan-anticheat-advanced-detections-hack-blocker.25638/

Am going to try with world guard disabled.

**Comment by DangerAngel97** [comment]
It was world guard. What should I say to them?

**Comment by DangerAngel97** [comment]
https://timings.spigotmc.org/?url=dasatexaga

**Comment by DangerAngel97** [comment]
They have no issue reporting on their github. I guess I will have to go without worldguard.
https://github.com/sk89q/WorldGuard

**Comment by mcmonkey4eva** [comment]
bottom of the readme links to their issue tracker

**Comment by DangerAngel97** [comment]
Page not loading.

**Comment by mcmonkey4eva** [comment]
Yeah, looks momentarily down. I guess wait an hour or two and try it again.
