### ISSUE TITLE
Sentinel cannot be Zombie type.

### ISSUE THREAD

**Issue by Zalakoth** [mcmonkey4eva/Sentinel#31]
I had an issue with assigning the sentinel trait to one of my NPCs to where whenever I attacked him, the whole server crashed. Luckily I know how to read and found the issue, but thought it would help for you to fix. Turns out you cannot assign the trait to an NPC with the type, "Zombie" Here are the logs in case you need it:

[23:30:25 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_9_R2.ReportedException: Ticking entity
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:808) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_9_R1/CraftWorld
	at org.mcmonkey.sentinel.SentinelTrait.getEntityForID(SentinelTrait.java:958) ~[?:?]
	at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:979) ~[?:?]
	at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1067) ~[?:?]
	at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:271) ~[?:?]
	at net.citizensnpcs.npc.entity.ZombieController$EntityZombieNPC.M(ZombieController.java:178) ~[?:?]
	at net.minecraft.server.v1_9_R2.EntityInsentient.doTick(EntityInsentient.java:650) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityLiving.n(EntityLiving.java:1928) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityInsentient.n(EntityInsentient.java:489) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityMonster.n(EntityMonster.java:24) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityZombie.n(EntityZombie.java:176) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityLiving.m(EntityLiving.java:1784) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityInsentient.m(EntityInsentient.java:249) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityMonster.m(EntityMonster.java:28) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityZombie.m(EntityZombie.java:233) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.World.entityJoinedWorld(World.java:1617) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.World.g(World.java:1592) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.World.tickEntities(World.java:1426) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.WorldServer.tickEntities(WorldServer.java:632) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:797) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	... 4 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_9_R1.CraftWorld
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
	at org.mcmonkey.sentinel.SentinelTrait.getEntityForID(SentinelTrait.java:958) ~[?:?]
	at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:979) ~[?:?]
	at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1067) ~[?:?]
	at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:271) ~[?:?]
	at net.citizensnpcs.npc.entity.ZombieController$EntityZombieNPC.M(ZombieController.java:178) ~[?:?]
	at net.minecraft.server.v1_9_R2.EntityInsentient.doTick(EntityInsentient.java:650) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityLiving.n(EntityLiving.java:1928) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityInsentient.n(EntityInsentient.java:489) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityMonster.n(EntityMonster.java:24) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityZombie.n(EntityZombie.java:176) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityLiving.m(EntityLiving.java:1784) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityInsentient.m(EntityInsentient.java:249) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityMonster.m(EntityMonster.java:28) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityZombie.m(EntityZombie.java:233) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.World.entityJoinedWorld(World.java:1617) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.World.g(World.java:1592) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.World.tickEntities(World.java:1426) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.WorldServer.tickEntities(WorldServer.java:632) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:797) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	... 4 more
[23:30:25 ERROR]: 	Cause of unexpected exception was
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_9_R1/CraftWorld
	at org.mcmonkey.sentinel.SentinelTrait.getEntityForID(SentinelTrait.java:958) ~[?:?]
	at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:979) ~[?:?]
	at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1067) ~[?:?]
	at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:271) ~[?:?]
	at net.citizensnpcs.npc.entity.ZombieController$EntityZombieNPC.M(ZombieController.java:178) ~[?:?]
	at net.minecraft.server.v1_9_R2.EntityInsentient.doTick(EntityInsentient.java:650) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityLiving.n(EntityLiving.java:1928) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityInsentient.n(EntityInsentient.java:489) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityMonster.n(EntityMonster.java:24) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityZombie.n(EntityZombie.java:176) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityLiving.m(EntityLiving.java:1784) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityInsentient.m(EntityInsentient.java:249) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityMonster.m(EntityMonster.java:28) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.EntityZombie.m(EntityZombie.java:233) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.World.entityJoinedWorld(World.java:1617) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.World.g(World.java:1592) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.World.tickEntities(World.java:1426) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.WorldServer.tickEntities(WorldServer.java:632) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:797) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_9_R1.CraftWorld
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-d8637df]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
	... 24 more

**Comment by mcmonkey4eva** [comment]
... You're running Sentinel for 1.9.2 on a 1.9.4 server. Please update your plugins!

**Comment by Zalakoth** [comment]
No... Im running your most up to date version of the Plugin. Im simply saying that you cannot set the NPC type as zombie and have it be a Sentinel. I found the problem which I had also already stated, and i am simply putting it here for the knowledge of others who come across this issue, and or a possible bug fix.

**Comment by mcmonkey4eva** [comment]
@Zalakoth No... you are not. You are running an outdated version of Sentinel. Please update from http://ci.citizensnpcs.co/job/Sentinel/
