### ISSUE TITLE
ISSUE: Player move error on sentinel trait

### ISSUE THREAD

**Issue by hmmcrunchy** [mcmonkey4eva/Sentinel#40]
HI there I get this spamming the console, not all the time, im trying to see what starts it off will report back if I find out 

error 👍 
```
[18:10:27 ERROR]: Could not pass event PlayerMoveEvent to Citizens v2.0.19-SNAPS
HOT (build 1374)
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:310) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.jav
a:607) [spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [s
pigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPosition
Look.a(SourceFile:18) [spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:
13) [spigot.jar:git-Spigot-6016ac7-10c10b3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_20]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_20]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.ja
r:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:
733) [spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:
399) [spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:
672) [spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.jav
a:571) [spigot.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_20]
Caused by: java.lang.IllegalArgumentException: Cannot measure distance between w
orld_nether and world
        at org.bukkit.Location.distanceSquared(Location.java:456) ~[spigot.jar:g
it-Spigot-6016ac7-10c10b3]
        at org.mcmonkey.sentinel.SentinelTrait.onPlayerMovesInRange(SentinelTrai
t.java:1170) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor186.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_20]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_20]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        ... 15 more
```

**Comment by mcmonkey4eva** [comment]
oh screw me, that's entirely my fault. I'll fix that.

**Comment by hmmcrunchy** [comment]
XD epic thanks
