### ISSUE TITLE
Path and sentinel

### ISSUE THREAD

**Issue by ricardoandren** [mcmonkey4eva/Sentinel#42]
If i use the /npc path command when the npc is a sentinel the server stops i tried everything

**Comment by mcmonkey4eva** [comment]
Huh? Do you have any error messages for this? I have fully functional pathed NPCs on test servers.

**Comment by ricardoandren** [comment]
[16:09:30] [Server thread/WARN]: [Citizens] Task #124 for Citizens v2.0.17-SNAPSHOT (build 1316) generated an exception
net.minecraft.server.v1_9_R1.ReportedException: Ticking player
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-7fc5cd8]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:686) [craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:361) [craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:635) [craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:539) [craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-7fc5cd8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NoClassDefFoundError: net/citizensnpcs/trait/waypoint/WaypointProvider$EnumerableWaypointProvider
	at org.mcmonkey.sentinel.SentinelTrait.nearestPathPoint(SentinelTrait.java:1038) ~[?:?]
	at org.mcmonkey.sentinel.SentinelTrait.getGuardZone(SentinelTrait.java:1025) ~[?:?]
	at org.mcmonkey.sentinel.SentinelTrait.findBestTarget(SentinelTrait.java:924) ~[?:?]
	at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:987) ~[?:?]
	at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1067) ~[?:?]
	at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:425) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:268) ~[?:?]
	at net.citizensnpcs.npc.entity.EntityHumanNPC.m(EntityHumanNPC.java:297) ~[?:?]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1492) ~[craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1470) ~[craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-7fc5cd8]
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:42) ~[?:?]
	... 7 more
[16:09:30]

**Comment by mcmonkey4eva** [comment]
Ah. Er... update your server, you're running old versions of things. http://wiki.citizensnpcs.co/Versions

**Comment by ricardoandren** [comment]
Ow k we still run on 1.9.2 because of plugins running on old versions

**Comment by ricardoandren** [comment]
Yeah we are going to update it to 1.9.4 so i find the versions of it thanks by the way :)

**Comment by ricardoandren** [comment]
the server i mean by that
