### ISSUE TITLE
/NPC Inventory Problem with arrows. [Version 1.10.2] Last Version Of Sentinel.

### ISSUE THREAD

**Issue by NosmaStew** [mcmonkey4eva/Sentinel#57]
Error : 

[22:31:11 INFO]: [Citizens] Exception while updating 8: Tipped Arrows must have at least 1 effect.
[22:31:11 WARN]: java.lang.IllegalArgumentException: Tipped Arrows must have at least 1 effect
[22:31:11 WARN]:        at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[22:31:11 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftTippedArrow.setBasePotionData(CraftTippedArrow.java:114)
[22:31:11 WARN]:        at org.mcmonkey.sentinel.SentinelTrait.fireArrow(SentinelTrait.java:404)
[22:31:11 WARN]:        at org.mcmonkey.sentinel.SentinelTrait.tryAttack(SentinelTrait.java:697)
[22:31:11 WARN]:        at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1042)
[22:31:11 WARN]:        at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1121)
[22:31:11 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430)
[22:31:11 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:271)
[22:31:11 WARN]:        at net.citizensnpcs.npc.entity.EntityHumanNPC.m(EntityHumanNPC.java:306)
[22:31:11 WARN]:        at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1622)
[22:31:11 WARN]:        at net.minecraft.server.v1_10_R1.World.g(World.java:1597)
[22:31:11 WARN]:        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:51)
[22:31:11 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[22:31:11 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[22:31:11 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741)
[22:31:11 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
[22:31:11 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
[22:31:11 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
[22:31:11 WARN]:        at java.lang.Thread.run(Unknown Source)

Problem : 
When i add on the NPC inventory Arrows with Effects after playing or closing the server, restarting etc. the effected arrows are becoming With no effects arrows and i get this error in my console. Also if the NPC has the arrows with no effects when NPC is shooting the arrows going to the ground than shooting in the player/entity.

**Comment by mcmonkey4eva** [comment]
I pushed a fix that will "help" by not reporting the error when it occurs.

However, the underlying error is still present... in Citizens2.

Basically, Citizens loses potion-related metadata on items across restarts, and that causes issues.

I've placed the relevant issue here: https://github.com/CitizensDev/Citizens2/issues/868

When that issue is fixed, this issue should be as well.

**Comment by NosmaStew** [comment]
Thank you for explaining ! i will wait for a new version for the bug fixes!

**Comment by mcmonkey4eva** [comment]
It's actually already available as of yesterday.

**Comment by NosmaStew** [comment]
Sorry for late answer. I am not checking the mails in here. Hope you fixed
the issue because i will use your plugin some day for my server when it's
done!
