### ISSUE TITLE
[BUG] Ranged sentinels with Flame-enchanted bows cause errors

### ISSUE THREAD

**Issue by PsychoLynx** [mcmonkey4eva/Sentinel#66]
Created an NPC, equipped them with bow with Flame-enchantment. He fires arrows (although no fire arrows), but this stackrate is printed in the console.

[10:22:46] [Server thread/INFO]: [Citizens] Exception while updating 172: null.
[10:22:46] [Server thread/WARN]: java.lang.NullPointerException
[10:22:46] [Server thread/WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.fireArrow(SentinelTrait.java:447)
[10:22:46] [Server thread/WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.tryAttack(SentinelTrait.java:881)
[10:22:46] [Server thread/WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1290)
[10:22:46] [Server thread/WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1372)
[10:22:46] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430)
[10:22:46] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:271)
[10:22:46] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_10_R1.entity.EntityHumanNPC.m(EntityHumanNPC.java:309)
[10:22:46] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1738)
[10:22:46] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.World.g(World.java:1713)
[10:22:46] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_10_R1.util.NMSImpl.tick(NMSImpl.java:839)
[10:22:46] [Server thread/WARN]: 	at net.citizensnpcs.util.NMS.tick(NMS.java:246)
[10:22:46] [Server thread/WARN]: 	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:34)
[10:22:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[10:22:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[10:22:46] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:781)
[10:22:46] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[10:22:46] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725)
[10:22:46] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624)
[10:22:46] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by mcmonkey4eva** [comment]
Are you on the latest build? I can't replicate that error.

**Comment by mcmonkey4eva** [comment]
Also, I just pushed a new version that supports the FLAME enchantment by lighting shot arrows on fire.

**Comment by PsychoLynx** [comment]
Seems to have fixed it. Thanks :)
