### ISSUE TITLE
Error has occurred while adding trait to an NPC

### ISSUE THREAD

**Issue by zombieknifer223** [mcmonkey4eva/Sentinel#88]
I made an NPC and tried adding a trait, and then I got this.

[16:20:28 INFO]: [CommandEdit] Command Edit catched the following command: /npc create Guard
[16:20:33 INFO]: ZombieKnifer223 issued server command: /npc look
[16:20:33 INFO]: [CommandEdit] Command Edit catched the following command: /npc look
[16:20:40 INFO]: ZombieKnifer223 issued server command: /npc create Guard
[16:20:40 INFO]: [CommandEdit] Command Edit catched the following command: /npc create Guard
[16:20:41 INFO]: ZombieKnifer223 issued server command: /npc look
[16:20:41 INFO]: [CommandEdit] Command Edit catched the following command: /npc look
[16:20:48 INFO]: ZombieKnifer223 issued server command: /trait sentinel
[16:20:48 INFO]: [CommandEdit] Command Edit catched the following command: /trait sentinel
**_[16:20:48 WARN]: java.lang.NoSuchFieldError: SHULKER_**
[16:20:48 WARN]: 	at org.mcmonkey.sentinel.SentinelTarget.<clinit>(SentinelTarget.java:14)
[16:20:48 WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.onAttach(SentinelTrait.java:322)
[16:20:48 WARN]: 	at net.citizensnpcs.api.trait.Trait.linkToNPC(Trait.java:46)
[16:20:48 WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:99)
[16:20:48 WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:88)
[16:20:48 WARN]: 	at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
[16:20:48 WARN]: 	at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
[16:20:48 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:20:48 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:20:48 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:20:48 WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:20:48 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[16:20:48 WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[16:20:48 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[16:20:48 WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:238)
[16:20:48 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:20:48 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:20:48 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[16:20:48 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[16:20:48 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[16:20:48 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:20:48 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:20:48 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:20:48 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:20:48 WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[16:20:48 WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:20:48 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[16:20:48 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:20:48 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:20:48 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:20:48 WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by zombieknifer223** [comment]
Okay! Now when I tried the alternative way (seen in log) it shows a different error message!

[16:25:45 INFO]: ZombieKnifer223 issued server command: /npc create Guard --trait sentinel
[16:25:45 INFO]: [CommandEdit] Command Edit catched the following command: /npc create Guard --trait sentinel
**_[16:25:45 WARN]: java.lang.NoClassDefFoundError: Could not initialize class org.mcmonkey.sentinel.SentinelTarget_**
[16:25:45 WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.onAttach(SentinelTrait.java:322)
[16:25:45 WARN]: 	at net.citizensnpcs.api.trait.Trait.linkToNPC(Trait.java:46)
[16:25:45 WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:99)
[16:25:45 WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:385)
[16:25:45 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:25:45 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:25:45 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:25:45 WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:25:45 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[16:25:45 WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[16:25:45 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[16:25:45 WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:238)
[16:25:45 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:25:45 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:25:45 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[16:25:45 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[16:25:45 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[16:25:45 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:25:45 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:25:45 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:25:45 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:25:45 WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[16:25:45 WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:25:45 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[16:25:45 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:25:45 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:25:45 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:25:45 WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by mcmonkey4eva** [comment]
Sentinel does not support minecraft version 1.8.8, please update your server to 1.9 or 1.10

**Comment by Pacorus** [comment]
hi im on spigot 1.10 And if I want to create a Sentinel comes this error message what should I do?
20:11:02 CONSOLE: WARN]: at org.mcmonkey.sentinel.SentinelTrait.onAttach(SentinelTrait.java:414)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.api.trait.Trait.linkToNPC(Trait.java:46)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:100)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:89)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
20:11:02 CONSOLE: WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:11:02 CONSOLE: WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:11:02 CONSOLE: WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:11:02 CONSOLE: WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
20:11:02 CONSOLE: WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
20:11:02 CONSOLE: WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
20:11:02 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
20:11:02 CONSOLE: WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20:11:02 CONSOLE: WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
20:11:02 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)

**Comment by mcmonkey4eva** [comment]
@Pacorus latest Sentinel is built for 1.11, so either update to that or use an older Sentinel build from https://wiki.citizensnpcs.co/Versions#Sentinel_Versions
