### ISSUE TITLE
Failed to import Sentry to Sentinel

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#92]
Hello,
When I try to import with the command, it show me an error.

Spigot version : 1.8.8
Citizens version : 2.0.16-SNAPSHOT (build 1267)
Sentry version : 1.8.5
Sentinel version : sentinel-0.8.jar (#67) & sentinel-0.6.jar

<img src="http://img03.imgland.net/ISEnwiD.png	"/>

```
[19:11:42 INFO]: ******* issued server command: /sentinel sentryimport
[19:11:42 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sentinel' in plugin Sentinel v0.8 (build 67)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.mcmonkey.sentinel.SentinelTarget
        at org.mcmonkey.sentinel.SentinelTrait.onAttach(SentinelTrait.java:374) ~[?:?]
        at net.citizensnpcs.api.trait.Trait.linkToNPC(Trait.java:46) ~[?:?]
        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:99) ~[?:?]
        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:88) ~[?:?]
        at org.mcmonkey.sentinel.SentryImport.PerformImport(SentryImport.java:31) ~[?:?]
        at org.mcmonkey.sentinel.SentinelPlugin.onCommand(SentinelPlugin.java:155) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        ... 15 more
```

**Comment by mcmonkey4eva** [comment]
Sentinel does not support minecraft 1.8

**Comment by Blamo27** [comment]
Same thing in 1.9.

**Comment by mcmonkey4eva** [comment]
Make you sure you have the 1.9 version of Sentinel, not the 1.10 version.
