### ISSUE TITLE
Could not initialize class org.mcmonkey.sentinel.SentinelTarget

### ISSUE THREAD

**Issue by xXMrGXx** [mcmonkey4eva/Sentinel#99]
Updated to the newest Sentinel version (0.9), and got this error on /trait sentinel

Server: This server is running CraftBukkit version git-Spigot-c55900f-9af379f (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)
Citizens: =====[ Citizens v2.0.19-SNAPSHOT (build 1374) ]=====

Ingame:
```
[21:13:30] [Client thread/INFO]: [CHAT] Bitte melde diesen Fehler: [Siehe Konsole]
[21:13:30] [Client thread/INFO]: [CHAT] java.lang.NoClassDefFoundError: Could not initialize class org.mcmonkey.sentinel.SentinelTarget
```

Server Log:

```
[21:13:30] [Server thread/INFO]: xXMrGxx issued server command: /trait sentinel
[21:13:30] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class org.mcmonkey.sentinel.SentinelTarget
[21:13:30] [Server thread/WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.onAttach(SentinelTrait.java:384)
[21:13:30] [Server thread/WARN]: 	at net.citizensnpcs.api.trait.Trait.linkToNPC(Trait.java:46)
[21:13:30] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:100)
[21:13:30] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:89)
[21:13:30] [Server thread/WARN]: 	at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
[21:13:30] [Server thread/WARN]: 	at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
[21:13:30] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:13:30] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:13:30] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:13:30] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:13:30] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[21:13:30] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[21:13:30] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[21:13:30] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[21:13:30] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:13:30] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:13:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[21:13:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
[21:13:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
[21:13:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:13:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:13:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:13:30] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:13:30] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:13:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[21:13:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733)
[21:13:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
[21:13:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
[21:13:30] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
[21:13:30] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mcmonkey4eva** [comment]
Update your server to 1.11, or downdate Sentinel to the version built for 1.10: https://wiki.citizensnpcs.co/Versions
